import React, { useState, useEffect } from 'react'
import axios from 'axios';
import Navbar from './Navbar';
import './Navbar_style.css';
import './HomePage.css';
import Card from './Card.jsx'

const traindata = {
	"status": true,
	"message": "Success",
	"timestamp": 1707659796198,
	"data": [
		{
			"train_number": "20902",
			"train_name": "Vande Bharat Express",
			"run_days": [
				"Mon",
				"Tue",
				"Thu",
				"Fri",
				"Sat",
				"Sun"
			],
			"train_src": "GNC",
			"train_dstn": "MMCT",
			"from_std": "15:56",
			"from_sta": "15:53",
			"local_train_from_sta": 953,
			"to_sta": "17:10",
			"to_std": "17:13",
			"from_day": 0,
			"to_day": 0,
			"d_day": 0,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 0,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "1:14",
			"special_train": false,
			"train_type": "VBEX",
			"score": 30,
			"score_train_type": 10,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 1,
			"score_duration": 10,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"CC",
				"EC"
			]
		},
		{
			"train_number": "12952",
			"train_name": "Rajdhani Express",
			"run_days": [
				"Mon",
				"Tue",
				"Wed",
				"Thu",
				"Fri",
				"Sat",
				"Sun"
			],
			"train_src": "NDLS",
			"train_dstn": "MMCT",
			"from_std": "03:50",
			"from_sta": "03:40",
			"local_train_from_sta": 1660,
			"to_sta": "05:13",
			"to_std": "05:18",
			"from_day": 1,
			"to_day": 1,
			"d_day": 1,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 0,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "1:23",
			"special_train": false,
			"train_type": "RAJ",
			"score": 25,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 1,
			"score_duration": 10,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"3A",
				"2A",
				"1A"
			]
		},
		{
			"train_number": "82902",
			"train_name": "IRCTC Tejas Express",
			"run_days": [
				"Mon",
				"Tue",
				"Wed",
				"Fri",
				"Sat",
				"Sun"
			],
			"train_src": "ADI",
			"train_dstn": "MMCT",
			"from_std": "07:59",
			"from_sta": "07:54",
			"local_train_from_sta": 474,
			"to_sta": "09:25",
			"to_std": "09:30",
			"from_day": 0,
			"to_day": 0,
			"d_day": 0,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 1,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "1:26",
			"special_train": false,
			"train_type": "TEJ",
			"score": 25,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 1,
			"score_duration": 10,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"CC",
				"EC"
			]
		},
		{
			"train_number": "12904",
			"train_name": "Golden Temple Mail",
			"run_days": [
				"Mon",
				"Tue",
				"Wed",
				"Thu",
				"Fri",
				"Sat",
				"Sun"
			],
			"train_src": "ASR",
			"train_dstn": "MMCT",
			"from_std": "18:11",
			"from_sta": "18:01",
			"local_train_from_sta": 2521,
			"to_sta": "19:41",
			"to_std": "19:46",
			"from_day": 1,
			"to_day": 1,
			"d_day": 1,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 0,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "1:30",
			"special_train": false,
			"train_type": "MAIL EXPRESS",
			"score": 25,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 1,
			"score_duration": 10,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"SL",
				"3A",
				"2A",
				"1A"
			]
		},
		{
			"train_number": "16505",
			"train_name": "Gandhidham - KSR Bengaluru Express",
			"run_days": [
				"Tue"
			],
			"train_src": "GIMB",
			"train_dstn": "SBC",
			"from_std": "16:15",
			"from_sta": "16:05",
			"local_train_from_sta": 965,
			"to_sta": "17:46",
			"to_std": "17:51",
			"from_day": 0,
			"to_day": 0,
			"d_day": 0,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 1,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "1:31",
			"special_train": false,
			"train_type": "MEX",
			"score": 25,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 1,
			"score_duration": 10,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"2S",
				"SL",
				"3A",
				"2A",
				"1A"
			]
		},
		{
			"train_number": "12908",
			"train_name": "Sampark Kranti Express",
			"run_days": [
				"Tue",
				"Fri"
			],
			"train_src": "NZM",
			"train_dstn": "BDTS",
			"from_std": "04:05",
			"from_sta": "03:55",
			"local_train_from_sta": 1675,
			"to_sta": "05:37",
			"to_std": "05:39",
			"from_day": 1,
			"to_day": 1,
			"d_day": 1,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 0,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "1:32",
			"special_train": false,
			"train_type": "SKRT",
			"score": 25,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 1,
			"score_duration": 10,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"SL",
				"3A",
				"2A",
				"1A",
				"3E"
			]
		},
		{
			"train_number": "12215",
			"train_name": "Garib Rath Express",
			"run_days": [
				"Tue",
				"Wed",
				"Fri",
				"Sun"
			],
			"train_src": "DEE",
			"train_dstn": "BDTS",
			"from_std": "02:22",
			"from_sta": "02:17",
			"local_train_from_sta": 1577,
			"to_sta": "03:55",
			"to_std": "04:00",
			"from_day": 1,
			"to_day": 1,
			"d_day": 1,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 1,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "1:33",
			"special_train": false,
			"train_type": "GBR",
			"score": 25,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 1,
			"score_duration": 10,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"3A"
			]
		},
		{
			"train_number": "12954",
			"train_name": "August Kranti Rajdhani Express",
			"run_days": [
				"Mon",
				"Tue",
				"Wed",
				"Thu",
				"Fri",
				"Sat",
				"Sun"
			],
			"train_src": "NZM",
			"train_dstn": "MMCT",
			"from_std": "04:39",
			"from_sta": "04:29",
			"local_train_from_sta": 1709,
			"to_sta": "06:13",
			"to_std": "06:18",
			"from_day": 1,
			"to_day": 1,
			"d_day": 1,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 1,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "1:34",
			"special_train": false,
			"train_type": "RAJ",
			"score": 25,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 1,
			"score_duration": 10,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"3A",
				"2A",
				"1A"
			]
		},
		{
			"train_number": "22944",
			"train_name": "INDORE - DAUND SF Express",
			"run_days": [
				"Mon",
				"Tue",
				"Wed",
				"Thu",
				"Fri",
				"Sat",
				"Sun"
			],
			"train_src": "INDB",
			"train_dstn": "DD",
			"from_std": "23:58",
			"from_sta": "23:48",
			"local_train_from_sta": 1428,
			"to_sta": "01:32",
			"to_std": "01:37",
			"from_day": 0,
			"to_day": 1,
			"d_day": 0,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 0,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "1:34",
			"special_train": false,
			"train_type": "MAIL EXPRESS",
			"score": 25,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 1,
			"score_duration": 10,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"SL",
				"3A",
				"2A",
				"1A"
			]
		},
		{
			"train_number": "12934",
			"train_name": "Karnavati SF Express",
			"run_days": [
				"Mon",
				"Tue",
				"Wed",
				"Thu",
				"Fri",
				"Sat",
				"Sun"
			],
			"train_src": "ADI",
			"train_dstn": "MMCT",
			"from_std": "06:33",
			"from_sta": "06:28",
			"local_train_from_sta": 388,
			"to_sta": "08:08",
			"to_std": "08:13",
			"from_day": 0,
			"to_day": 0,
			"d_day": 0,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 1,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "1:35",
			"special_train": false,
			"train_type": "MAIL EXPRESS",
			"score": 25,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 1,
			"score_duration": 10,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"2S",
				"CC",
				"EV"
			]
		},
		{
			"train_number": "12010",
			"train_name": "Shatabdi Express",
			"run_days": [
				"Mon",
				"Tue",
				"Wed",
				"Thu",
				"Fri",
				"Sat"
			],
			"train_src": "ADI",
			"train_dstn": "MMCT",
			"from_std": "16:35",
			"from_sta": "16:30",
			"local_train_from_sta": 990,
			"to_sta": "18:10",
			"to_std": "18:15",
			"from_day": 0,
			"to_day": 0,
			"d_day": 0,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 1,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "1:35",
			"special_train": false,
			"train_type": "MAIL EXPRESS",
			"score": 25,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 1,
			"score_duration": 10,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"CC",
				"EC",
				"EV",
				"EA"
			]
		},
		{
			"train_number": "22660",
			"train_name": "Yog Nagari Rishikesh - Kochuveli SF Express",
			"run_days": [
				"Tue"
			],
			"train_src": "YNRK",
			"train_dstn": "KCVL",
			"from_std": "01:23",
			"from_sta": "01:15",
			"local_train_from_sta": 1515,
			"to_sta": "03:00",
			"to_std": "03:05",
			"from_day": 1,
			"to_day": 1,
			"d_day": 1,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 0,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "1:37",
			"special_train": false,
			"train_type": "SUF",
			"score": 25,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 1,
			"score_duration": 10,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"SL",
				"3A",
				"2A",
				"3E"
			]
		},
		{
			"train_number": "19028",
			"train_name": "Vivek Express",
			"run_days": [
				"Tue"
			],
			"train_src": "JAT",
			"train_dstn": "BDTS",
			"from_std": "09:03",
			"from_sta": "08:58",
			"local_train_from_sta": 1978,
			"to_sta": "10:40",
			"to_std": "10:45",
			"from_day": 1,
			"to_day": 1,
			"d_day": 1,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 0,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "1:37",
			"special_train": false,
			"train_type": "MAIL EXPRESS",
			"score": 25,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 1,
			"score_duration": 10,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"SL",
				"3A",
				"2A",
				"1A",
				"3E"
			]
		},
		{
			"train_number": "12432",
			"train_name": "Rajdhani Express",
			"run_days": [
				"Tue",
				"Wed",
				"Sun"
			],
			"train_src": "NZM",
			"train_dstn": "TVC",
			"from_std": "17:37",
			"from_sta": "17:27",
			"local_train_from_sta": 1047,
			"to_sta": "19:14",
			"to_std": "19:17",
			"from_day": 0,
			"to_day": 0,
			"d_day": 0,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 0,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "1:37",
			"special_train": false,
			"train_type": "RAJ",
			"score": 23,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 1,
			"score_duration": 8,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"3A",
				"2A",
				"1A"
			]
		},
		{
			"train_number": "12940",
			"train_name": "JAIPUR - PUNE SF Express",
			"run_days": [
				"Tue",
				"Sat"
			],
			"train_src": "JP",
			"train_dstn": "PUNE",
			"from_std": "23:29",
			"from_sta": "23:19",
			"local_train_from_sta": 1399,
			"to_sta": "01:08",
			"to_std": "01:13",
			"from_day": 0,
			"to_day": 1,
			"d_day": 0,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 0,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "1:39",
			"special_train": false,
			"train_type": "MAIL EXPRESS",
			"score": 23,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 1,
			"score_duration": 8,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"SL",
				"3A",
				"2A",
				"1A",
				"3E"
			]
		},
		{
			"train_number": "12902",
			"train_name": "Gujarat Mail",
			"run_days": [
				"Mon",
				"Tue",
				"Wed",
				"Thu",
				"Fri",
				"Sat",
				"Sun"
			],
			"train_src": "ADI",
			"train_dstn": "DDR",
			"from_std": "00:25",
			"from_sta": "00:20",
			"local_train_from_sta": 1460,
			"to_sta": "02:05",
			"to_std": "02:10",
			"from_day": 1,
			"to_day": 1,
			"d_day": 1,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 1,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "1:40",
			"special_train": false,
			"train_type": "MAIL EXPRESS",
			"score": 23,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 1,
			"score_duration": 8,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"2S",
				"SL",
				"3A",
				"2A",
				"1A",
				"3E"
			]
		},
		{
			"train_number": "12956",
			"train_name": "Jaipur - Mumbai Central SF Express",
			"run_days": [
				"Mon",
				"Tue",
				"Wed",
				"Thu",
				"Fri",
				"Sat",
				"Sun"
			],
			"train_src": "JP",
			"train_dstn": "MMCT",
			"from_std": "01:06",
			"from_sta": "00:56",
			"local_train_from_sta": 1496,
			"to_sta": "02:48",
			"to_std": "02:53",
			"from_day": 1,
			"to_day": 1,
			"d_day": 1,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 1,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "1:42",
			"special_train": false,
			"train_type": "SUF",
			"score": 23,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 1,
			"score_duration": 8,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"SL",
				"3A",
				"2A",
				"1A"
			]
		},
		{
			"train_number": "22664",
			"train_name": "Jodhpur - Chennai Egmore SF Express",
			"run_days": [
				"Tue"
			],
			"train_src": "JU",
			"train_dstn": "MS",
			"from_std": "09:56",
			"from_sta": "09:51",
			"local_train_from_sta": 591,
			"to_sta": "11:40",
			"to_std": "11:45",
			"from_day": 0,
			"to_day": 0,
			"d_day": 0,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 0,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "1:44",
			"special_train": false,
			"train_type": "SUF",
			"score": 23,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 1,
			"score_duration": 8,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"SL",
				"3A",
				"2A"
			]
		},
		{
			"train_number": "16734",
			"train_name": "Okha - Mandapam Express",
			"run_days": [
				"Tue"
			],
			"train_src": "OKHA",
			"train_dstn": "MDP",
			"from_std": "19:31",
			"from_sta": "19:21",
			"local_train_from_sta": 1161,
			"to_sta": "21:15",
			"to_std": "21:20",
			"from_day": 0,
			"to_day": 0,
			"d_day": 0,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 0,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "1:44",
			"special_train": false,
			"train_type": "MEX",
			"score": 23,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 1,
			"score_duration": 8,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"SL",
				"3A",
				"2A"
			]
		},
		{
			"train_number": "22497",
			"train_name": "Humsafar Express",
			"run_days": [
				"Tue"
			],
			"train_src": "SGNR",
			"train_dstn": "TPJ",
			"from_std": "09:32",
			"from_sta": "09:27",
			"local_train_from_sta": 2007,
			"to_sta": "11:17",
			"to_std": "11:22",
			"from_day": 1,
			"to_day": 1,
			"d_day": 1,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 1,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "1:45",
			"special_train": false,
			"train_type": "HMSR",
			"score": 23,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 1,
			"score_duration": 8,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"3A"
			]
		},
		{
			"train_number": "22946",
			"train_name": "Saurashtra Mail",
			"run_days": [
				"Mon",
				"Tue",
				"Wed",
				"Thu",
				"Fri",
				"Sat",
				"Sun"
			],
			"train_src": "OKHA",
			"train_dstn": "MMCT",
			"from_std": "22:20",
			"from_sta": "22:15",
			"local_train_from_sta": 1335,
			"to_sta": "00:05",
			"to_std": "00:10",
			"from_day": 0,
			"to_day": 1,
			"d_day": 0,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 1,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "1:45",
			"special_train": false,
			"train_type": "MEX",
			"score": 23,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 1,
			"score_duration": 8,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"SL",
				"3A",
				"2A",
				"1A",
				"3E"
			]
		},
		{
			"train_number": "14701",
			"train_name": "Amrapur Aravali Express",
			"run_days": [
				"Mon",
				"Tue",
				"Wed",
				"Thu",
				"Fri",
				"Sat",
				"Sun"
			],
			"train_src": "SGNR",
			"train_dstn": "BDTS",
			"from_std": "00:06",
			"from_sta": "00:01",
			"local_train_from_sta": 2881,
			"to_sta": "01:52",
			"to_std": "01:57",
			"from_day": 2,
			"to_day": 2,
			"d_day": 2,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 1,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "1:46",
			"special_train": false,
			"train_type": "MEX",
			"score": 23,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 1,
			"score_duration": 8,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"SL",
				"3A",
				"2A"
			]
		},
		{
			"train_number": "12980",
			"train_name": "JP BDTS EXP",
			"run_days": [
				"Tue",
				"Thu",
				"Sat"
			],
			"train_src": "JP",
			"train_dstn": "BDTS",
			"from_std": "07:13",
			"from_sta": "07:03",
			"local_train_from_sta": 1863,
			"to_sta": "08:59",
			"to_std": "09:04",
			"from_day": 1,
			"to_day": 1,
			"d_day": 1,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 0,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "1:46",
			"special_train": false,
			"train_type": "MAIL EXPRESS",
			"score": 23,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 1,
			"score_duration": 8,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"SL",
				"3A",
				"2A",
				"1A",
				"3E"
			]
		},
		{
			"train_number": "19038",
			"train_name": "Avadh Express",
			"run_days": [
				"Mon",
				"Tue",
				"Wed",
				"Thu",
				"Fri",
				"Sat",
				"Sun"
			],
			"train_src": "BJU",
			"train_dstn": "BDTS",
			"from_std": "21:38",
			"from_sta": "21:30",
			"local_train_from_sta": 2730,
			"to_sta": "23:24",
			"to_std": "23:29",
			"from_day": 1,
			"to_day": 1,
			"d_day": 1,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 1,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "1:46",
			"special_train": false,
			"train_type": "MEX",
			"score": 23,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 1,
			"score_duration": 8,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"2S",
				"SL",
				"3A",
				"2A",
				"1A",
				"3E"
			]
		},
		{
			"train_number": "12972",
			"train_name": "Bhavnagar T - Mumbai Bandra T SF Express",
			"run_days": [
				"Mon",
				"Tue",
				"Wed",
				"Thu",
				"Fri",
				"Sat",
				"Sun"
			],
			"train_src": "BVC",
			"train_dstn": "BDTS",
			"from_std": "01:37",
			"from_sta": "01:32",
			"local_train_from_sta": 1532,
			"to_sta": "03:24",
			"to_std": "03:29",
			"from_day": 1,
			"to_day": 1,
			"d_day": 1,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 0,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "1:47",
			"special_train": false,
			"train_type": "SUF",
			"score": 23,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 1,
			"score_duration": 8,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"SL",
				"3A",
				"2A",
				"1A"
			]
		},
		{
			"train_number": "12655",
			"train_name": "Navjeevan SF Express",
			"run_days": [
				"Mon",
				"Tue",
				"Wed",
				"Thu",
				"Fri",
				"Sat",
				"Sun"
			],
			"train_src": "ADI",
			"train_dstn": "MAS",
			"from_std": "22:57",
			"from_sta": "22:52",
			"local_train_from_sta": 1372,
			"to_sta": "00:44",
			"to_std": "00:49",
			"from_day": 0,
			"to_day": 1,
			"d_day": 0,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 1,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "1:47",
			"special_train": false,
			"train_type": "SUF",
			"score": 23,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 1,
			"score_duration": 8,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"SL",
				"3A",
				"2A",
				"1A",
				"3E"
			]
		},
		{
			"train_number": "22473",
			"train_name": "Bikaner - Mumbai Bandra T SF Express",
			"run_days": [
				"Tue"
			],
			"train_src": "BKN",
			"train_dstn": "BDTS",
			"from_std": "06:03",
			"from_sta": "05:58",
			"local_train_from_sta": 1798,
			"to_sta": "07:51",
			"to_std": "07:56",
			"from_day": 1,
			"to_day": 1,
			"d_day": 1,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 1,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "1:48",
			"special_train": false,
			"train_type": "SUF",
			"score": 23,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 1,
			"score_duration": 8,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"SL",
				"3A",
				"2A",
				"3E"
			]
		},
		{
			"train_number": "11089",
			"train_name": "Bhagat ki Kothi - Pune Express",
			"run_days": [
				"Tue"
			],
			"train_src": "BGKT",
			"train_dstn": "PUNE",
			"from_std": "22:02",
			"from_sta": "21:57",
			"local_train_from_sta": 1317,
			"to_sta": "23:51",
			"to_std": "23:56",
			"from_day": 0,
			"to_day": 0,
			"d_day": 0,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 1,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "1:49",
			"special_train": false,
			"train_type": "MEX",
			"score": 21,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 1,
			"score_duration": 6,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"SL",
				"3A",
				"2A"
			]
		},
		{
			"train_number": "12962",
			"train_name": "Avantika SF Express",
			"run_days": [
				"Mon",
				"Tue",
				"Wed",
				"Thu",
				"Fri",
				"Sat",
				"Sun"
			],
			"train_src": "INDB",
			"train_dstn": "MMCT",
			"from_std": "00:38",
			"from_sta": "00:30",
			"local_train_from_sta": 1470,
			"to_sta": "02:29",
			"to_std": "02:34",
			"from_day": 1,
			"to_day": 1,
			"d_day": 1,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 1,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "1:51",
			"special_train": false,
			"train_type": "MAIL EXPRESS",
			"score": 21,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 1,
			"score_duration": 6,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"2S",
				"SL",
				"3A",
				"2A",
				"1A",
				"3E"
			]
		},
		{
			"train_number": "12960",
			"train_name": "Bhuj - Mumbai Bandra T SF Express",
			"run_days": [
				"Tue"
			],
			"train_src": "BHUJ",
			"train_dstn": "BDTS",
			"from_std": "05:19",
			"from_sta": "05:14",
			"local_train_from_sta": 1754,
			"to_sta": "07:10",
			"to_std": "07:15",
			"from_day": 1,
			"to_day": 1,
			"d_day": 1,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 0,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "1:51",
			"special_train": false,
			"train_type": "SUF",
			"score": 21,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 1,
			"score_duration": 6,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"SL",
				"3A",
				"2A"
			]
		},
		{
			"train_number": "12928",
			"train_name": "EKTA NAGAR - DADAR WESTERN SF Express",
			"run_days": [
				"Mon",
				"Tue",
				"Wed",
				"Thu",
				"Fri",
				"Sat",
				"Sun"
			],
			"train_src": "EKNR",
			"train_dstn": "DDR",
			"from_std": "23:05",
			"from_sta": "22:50",
			"local_train_from_sta": 1370,
			"to_sta": "00:56",
			"to_std": "01:01",
			"from_day": 0,
			"to_day": 1,
			"d_day": 0,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 1,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "1:51",
			"special_train": false,
			"train_type": "MAIL EXPRESS",
			"score": 21,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 1,
			"score_duration": 6,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"2S",
				"SL",
				"3A",
				"2A",
				"1A",
				"3E"
			]
		},
		{
			"train_number": "12479",
			"train_name": "Suryanagari SF Express",
			"run_days": [
				"Mon",
				"Tue",
				"Wed",
				"Thu",
				"Fri",
				"Sat",
				"Sun"
			],
			"train_src": "JU",
			"train_dstn": "BDTS",
			"from_std": "05:30",
			"from_sta": "05:25",
			"local_train_from_sta": 1765,
			"to_sta": "07:22",
			"to_std": "07:27",
			"from_day": 1,
			"to_day": 1,
			"d_day": 1,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 0,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "1:52",
			"special_train": false,
			"train_type": "SUF",
			"score": 21,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 2,
			"score_duration": 6,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"SL",
				"3A",
				"2A",
				"1A",
				"3E"
			]
		},
		{
			"train_number": "12930",
			"train_name": "Intercity SF Express",
			"run_days": [
				"Mon",
				"Tue",
				"Wed",
				"Thu",
				"Fri",
				"Sat",
				"Sun"
			],
			"train_src": "BRC",
			"train_dstn": "BL",
			"from_std": "17:10",
			"from_sta": "17:10",
			"local_train_from_sta": 1030,
			"to_sta": "19:02",
			"to_std": "19:07",
			"from_day": 0,
			"to_day": 0,
			"d_day": 0,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 6,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "1:52",
			"special_train": false,
			"train_type": "MAIL EXPRESS",
			"score": 21,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 2,
			"score_duration": 6,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"2S",
				"CC"
			]
		},
		{
			"train_number": "20968",
			"train_name": "Porbandar - Secunderabad Weekly SF Express",
			"run_days": [
				"Tue"
			],
			"train_src": "PBR",
			"train_dstn": "SC",
			"from_std": "11:31",
			"from_sta": "11:26",
			"local_train_from_sta": 686,
			"to_sta": "13:24",
			"to_std": "13:29",
			"from_day": 0,
			"to_day": 0,
			"d_day": 0,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 1,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "1:53",
			"special_train": false,
			"train_type": "SUF",
			"score": 21,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 2,
			"score_duration": 6,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"SL",
				"3A",
				"2A",
				"1A"
			]
		},
		{
			"train_number": "14707",
			"train_name": "RANAKPUR EXP",
			"run_days": [
				"Mon",
				"Tue",
				"Wed",
				"Thu",
				"Fri",
				"Sat",
				"Sun"
			],
			"train_src": "BKN",
			"train_dstn": "DDR",
			"from_std": "00:45",
			"from_sta": "00:40",
			"local_train_from_sta": 1480,
			"to_sta": "02:39",
			"to_std": "02:44",
			"from_day": 1,
			"to_day": 1,
			"d_day": 1,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 1,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "1:54",
			"special_train": false,
			"train_type": "MAIL EXPRESS",
			"score": 21,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 2,
			"score_duration": 6,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"SL",
				"3A",
				"2A"
			]
		},
		{
			"train_number": "12932",
			"train_name": "AHMEDABAD - MUMBAI CENTRAL AC Double Decker Exp",
			"run_days": [
				"Mon",
				"Tue",
				"Wed",
				"Thu",
				"Fri",
				"Sat"
			],
			"train_src": "ADI",
			"train_dstn": "MMCT",
			"from_std": "07:18",
			"from_sta": "07:13",
			"local_train_from_sta": 433,
			"to_sta": "09:12",
			"to_std": "09:17",
			"from_day": 0,
			"to_day": 0,
			"d_day": 0,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 1,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "1:54",
			"special_train": false,
			"train_type": "MAIL EXPRESS",
			"score": 21,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 2,
			"score_duration": 6,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"CC",
				"EV"
			]
		},
		{
			"train_number": "20960",
			"train_name": "Intercity SF Express",
			"run_days": [
				"Mon",
				"Tue",
				"Wed",
				"Thu",
				"Fri",
				"Sat",
				"Sun"
			],
			"train_src": "VDG",
			"train_dstn": "BL",
			"from_std": "21:20",
			"from_sta": "21:15",
			"local_train_from_sta": 1275,
			"to_sta": "23:14",
			"to_std": "23:17",
			"from_day": 0,
			"to_day": 0,
			"d_day": 0,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 1,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "1:54",
			"special_train": false,
			"train_type": "MAIL EXPRESS",
			"score": 21,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 2,
			"score_duration": 6,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"2S",
				"CC"
			]
		},
		{
			"train_number": "19667",
			"train_name": "Palace Queen Humsafar Express",
			"run_days": [
				"Tue"
			],
			"train_src": "UDZ",
			"train_dstn": "MYS",
			"from_std": "07:40",
			"from_sta": "07:30",
			"local_train_from_sta": 1890,
			"to_sta": "09:37",
			"to_std": "09:42",
			"from_day": 1,
			"to_day": 1,
			"d_day": 1,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 0,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "1:57",
			"special_train": false,
			"train_type": "HMSR",
			"score": 21,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 2,
			"score_duration": 6,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"SL",
				"3A"
			]
		},
		{
			"train_number": "12926",
			"train_name": "Paschim SF Express",
			"run_days": [
				"Mon",
				"Tue",
				"Wed",
				"Thu",
				"Fri",
				"Sat",
				"Sun"
			],
			"train_src": "ASR",
			"train_dstn": "MMCT",
			"from_std": "08:27",
			"from_sta": "08:17",
			"local_train_from_sta": 1937,
			"to_sta": "10:24",
			"to_std": "10:29",
			"from_day": 1,
			"to_day": 1,
			"d_day": 1,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 1,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "1:57",
			"special_train": false,
			"train_type": "SUF",
			"score": 21,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 2,
			"score_duration": 6,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"SL",
				"3A",
				"2A",
				"1A"
			]
		},
		{
			"train_number": "22956",
			"train_name": "Kutch SF Express",
			"run_days": [
				"Mon",
				"Tue",
				"Wed",
				"Thu",
				"Fri",
				"Sat",
				"Sun"
			],
			"train_src": "BHUJ",
			"train_dstn": "BDTS",
			"from_std": "04:46",
			"from_sta": "04:41",
			"local_train_from_sta": 1721,
			"to_sta": "06:45",
			"to_std": "06:50",
			"from_day": 1,
			"to_day": 1,
			"d_day": 1,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 2,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "1:59",
			"special_train": false,
			"train_type": "MAIL EXPRESS",
			"score": 21,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 2,
			"score_duration": 6,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"SL",
				"3A",
				"2A",
				"1A"
			]
		},
		{
			"train_number": "22928",
			"train_name": "Lokshakti SF Express",
			"run_days": [
				"Mon",
				"Tue",
				"Wed",
				"Thu",
				"Fri",
				"Sat",
				"Sun"
			],
			"train_src": "ADI",
			"train_dstn": "BDTS",
			"from_std": "22:33",
			"from_sta": "22:28",
			"local_train_from_sta": 1348,
			"to_sta": "00:32",
			"to_std": "00:37",
			"from_day": 0,
			"to_day": 1,
			"d_day": 0,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 2,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "1:59",
			"special_train": false,
			"train_type": "MAIL EXPRESS",
			"score": 21,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 2,
			"score_duration": 6,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"2S",
				"SL",
				"3A",
				"2A",
				"1A",
				"3E"
			]
		},
		{
			"train_number": "20483",
			"train_name": "BGKT DDR EXP",
			"run_days": [
				"Tue",
				"Fri"
			],
			"train_src": "BGKT",
			"train_dstn": "DDR",
			"from_std": "06:45",
			"from_sta": "06:40",
			"local_train_from_sta": 1840,
			"to_sta": "08:47",
			"to_std": "08:52",
			"from_day": 1,
			"to_day": 1,
			"d_day": 1,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 1,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "2:2",
			"special_train": false,
			"train_type": "MAIL EXPRESS",
			"score": 21,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 2,
			"score_duration": 6,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"SL",
				"3A",
				"2A",
				"3E"
			]
		},
		{
			"train_number": "19260",
			"train_name": "Bhavnagar T - Kochuveli Express",
			"run_days": [
				"Tue"
			],
			"train_src": "BVC",
			"train_dstn": "KCVL",
			"from_std": "17:22",
			"from_sta": "17:17",
			"local_train_from_sta": 1037,
			"to_sta": "19:24",
			"to_std": "19:34",
			"from_day": 0,
			"to_day": 0,
			"d_day": 0,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 1,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "2:2",
			"special_train": false,
			"train_type": "MEX",
			"score": 21,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 2,
			"score_duration": 6,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"SL",
				"3A",
				"2A"
			]
		},
		{
			"train_number": "20903",
			"train_name": "EKTA NAGAR - VARANASI Mahamana SF Express",
			"run_days": [
				"Tue"
			],
			"train_src": "EKNR",
			"train_dstn": "BSB",
			"from_std": "20:35",
			"from_sta": "20:20",
			"local_train_from_sta": 1220,
			"to_sta": "22:37",
			"to_std": "22:42",
			"from_day": 0,
			"to_day": 0,
			"d_day": 0,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 1,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "2:2",
			"special_train": false,
			"train_type": "MAIL EXPRESS",
			"score": 21,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 2,
			"score_duration": 6,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"SL",
				"3A",
				"2A",
				"1A"
			]
		},
		{
			"train_number": "22689",
			"train_name": "Ahmedabad - Yesvantpur SF Express",
			"run_days": [
				"Tue"
			],
			"train_src": "ADI",
			"train_dstn": "YPR",
			"from_std": "20:47",
			"from_sta": "20:42",
			"local_train_from_sta": 1242,
			"to_sta": "22:50",
			"to_std": "22:55",
			"from_day": 0,
			"to_day": 0,
			"d_day": 0,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 1,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "2:3",
			"special_train": false,
			"train_type": "SUF",
			"score": 21,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 2,
			"score_duration": 6,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"SL",
				"3A",
				"2A",
				"1A"
			]
		},
		{
			"train_number": "14807",
			"train_name": "Jodhpur - Mumbai Dadar Western Express",
			"run_days": [
				"Tue",
				"Fri",
				"Sun"
			],
			"train_src": "JU",
			"train_dstn": "DDR",
			"from_std": "15:30",
			"from_sta": "15:25",
			"local_train_from_sta": 925,
			"to_sta": "17:34",
			"to_std": "17:39",
			"from_day": 0,
			"to_day": 0,
			"d_day": 0,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 1,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "2:4",
			"special_train": false,
			"train_type": "MEX",
			"score": 21,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 2,
			"score_duration": 6,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"SL",
				"3A",
				"2A",
				"3E"
			]
		},
		{
			"train_number": "19218",
			"train_name": "Saurashtra Janta Express",
			"run_days": [
				"Mon",
				"Tue",
				"Wed",
				"Thu",
				"Fri",
				"Sat",
				"Sun"
			],
			"train_src": "VRL",
			"train_dstn": "BDTS",
			"from_std": "22:13",
			"from_sta": "22:08",
			"local_train_from_sta": 1328,
			"to_sta": "00:20",
			"to_std": "00:25",
			"from_day": 0,
			"to_day": 1,
			"d_day": 0,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 4,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "2:7",
			"special_train": false,
			"train_type": "MEX",
			"score": 19,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 2,
			"score_duration": 4,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"SL",
				"3A",
				"2A",
				"1A"
			]
		},
		{
			"train_number": "19483",
			"train_name": "Ahmedabad - Barauni Express",
			"run_days": [
				"Mon",
				"Tue",
				"Wed",
				"Fri",
				"Sat",
				"Sun"
			],
			"train_src": "ADI",
			"train_dstn": "BJU",
			"from_std": "02:30",
			"from_sta": "02:25",
			"local_train_from_sta": 145,
			"to_sta": "04:38",
			"to_std": "04:43",
			"from_day": 0,
			"to_day": 0,
			"d_day": 0,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 0,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "2:8",
			"special_train": false,
			"train_type": "MEX",
			"score": 19,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 2,
			"score_duration": 4,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"SL",
				"3A",
				"2A",
				"3E"
			]
		},
		{
			"train_number": "22954",
			"train_name": "Gujarat SF Express",
			"run_days": [
				"Mon",
				"Tue",
				"Wed",
				"Thu",
				"Fri",
				"Sat",
				"Sun"
			],
			"train_src": "ADI",
			"train_dstn": "MMCT",
			"from_std": "08:44",
			"from_sta": "08:39",
			"local_train_from_sta": 519,
			"to_sta": "10:52",
			"to_std": "10:57",
			"from_day": 0,
			"to_day": 0,
			"d_day": 0,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 6,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "2:8",
			"special_train": false,
			"train_type": "SUF",
			"score": 19,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 2,
			"score_duration": 4,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"2S",
				"CC"
			]
		},
		{
			"train_number": "22195",
			"train_name": "Virangana Lakshmibai Jhansi - Mumbai Bandra T SF Express",
			"run_days": [
				"Tue",
				"Mon"
			],
			"train_src": "VGLJ",
			"train_dstn": "BDST",
			"from_std": "10:15",
			"from_sta": "10:05",
			"local_train_from_sta": 2045,
			"to_sta": "12:25",
			"to_std": "12:30",
			"from_day": 1,
			"to_day": 1,
			"d_day": 1,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 1,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "2:10",
			"special_train": false,
			"train_type": "SUF",
			"score": 19,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 2,
			"score_duration": 4,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"SL",
				"3A",
				"2A",
				"3E"
			]
		},
		{
			"train_number": "22930",
			"train_name": "Vadodara - Dahanu Road SF Express",
			"run_days": [
				"Mon",
				"Tue",
				"Wed",
				"Thu",
				"Fri",
				"Sat",
				"Sun"
			],
			"train_src": "BRC",
			"train_dstn": "DRD",
			"from_std": "06:25",
			"from_sta": "06:25",
			"local_train_from_sta": 385,
			"to_sta": "08:37",
			"to_std": "08:40",
			"from_day": 0,
			"to_day": 0,
			"d_day": 0,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 7,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "2:12",
			"special_train": false,
			"train_type": "MAIL EXPRESS",
			"score": 19,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 2,
			"score_duration": 4,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"2S"
			]
		},
		{
			"train_number": "12833",
			"train_name": "Ahmedabad - Howrah SF Express",
			"run_days": [
				"Mon",
				"Tue",
				"Wed",
				"Thu",
				"Fri",
				"Sat",
				"Sun"
			],
			"train_src": "ADI",
			"train_dstn": "HWH",
			"from_std": "02:11",
			"from_sta": "02:04",
			"local_train_from_sta": 124,
			"to_sta": "04:26",
			"to_std": "04:31",
			"from_day": 0,
			"to_day": 0,
			"d_day": 0,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 1,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "2:15",
			"special_train": false,
			"train_type": "SUF",
			"score": 19,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 2,
			"score_duration": 4,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"SL",
				"3A",
				"2A"
			]
		},
		{
			"train_number": "20956",
			"train_name": "MAHUVA - SURAT SF Express",
			"run_days": [
				"Tue",
				"Wed",
				"Thu",
				"Sat",
				"Mon"
			],
			"train_src": "MHV",
			"train_dstn": "ST",
			"from_std": "04:19",
			"from_sta": "04:14",
			"local_train_from_sta": 1694,
			"to_sta": "06:35",
			"to_std": "06:35",
			"from_day": 1,
			"to_day": 1,
			"d_day": 1,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 0,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "2:16",
			"special_train": false,
			"train_type": "MAIL EXPRESS",
			"score": 19,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 2,
			"score_duration": 4,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"SL",
				"3A",
				"2A",
				"1A"
			]
		},
		{
			"train_number": "20908",
			"train_name": "Sayaji Nagari SF Express",
			"run_days": [
				"Mon",
				"Tue",
				"Wed",
				"Thu",
				"Fri",
				"Sat",
				"Sun"
			],
			"train_src": "BHUJ",
			"train_dstn": "DDR",
			"from_std": "07:30",
			"from_sta": "07:25",
			"local_train_from_sta": 1885,
			"to_sta": "09:50",
			"to_std": "09:53",
			"from_day": 1,
			"to_day": 1,
			"d_day": 1,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 6,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "2:20",
			"special_train": false,
			"train_type": "SUF",
			"score": 19,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 2,
			"score_duration": 4,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"2S",
				"SL",
				"3A",
				"2A",
				"1A"
			]
		},
		{
			"train_number": "19054",
			"train_name": "Muzaffarpur - Surat Express",
			"run_days": [
				"Tue"
			],
			"train_src": "MFP",
			"train_dstn": "ST",
			"from_std": "14:30",
			"from_sta": "14:20",
			"local_train_from_sta": 3740,
			"to_sta": "17:00",
			"to_std": "17:00",
			"from_day": 2,
			"to_day": 2,
			"d_day": 2,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 0,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "2:30",
			"special_train": false,
			"train_type": "MEX",
			"score": 19,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 3,
			"score_duration": 4,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"SL",
				"3A",
				"2A",
				"1A"
			]
		},
		{
			"train_number": "19020",
			"train_name": "Haridwar - Mumbai Bandra T Express",
			"run_days": [
				"Mon",
				"Tue",
				"Wed",
				"Thu",
				"Fri",
				"Sat",
				"Sun"
			],
			"train_src": "HW",
			"train_dstn": "BDTS",
			"from_std": "14:35",
			"from_sta": "14:25",
			"local_train_from_sta": 2305,
			"to_sta": "17:22",
			"to_std": "17:27",
			"from_day": 1,
			"to_day": 1,
			"d_day": 1,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 4,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "2:47",
			"special_train": false,
			"train_type": "MEX",
			"score": 19,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 3,
			"score_duration": 4,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"SL",
				"3A",
				"2A",
				"1A"
			]
		},
		{
			"train_number": "19034",
			"train_name": "Gujarat Queen",
			"run_days": [
				"Mon",
				"Tue",
				"Wed",
				"Thu",
				"Fri",
				"Sat",
				"Sun"
			],
			"train_src": "ADI",
			"train_dstn": "BL",
			"from_std": "20:13",
			"from_sta": "20:08",
			"local_train_from_sta": 1208,
			"to_sta": "23:02",
			"to_std": "23:07",
			"from_day": 0,
			"to_day": 0,
			"d_day": 0,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 9,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "2:49",
			"special_train": false,
			"train_type": "MEX",
			"score": 19,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 3,
			"score_duration": 4,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"2S",
				"CC"
			]
		},
		{
			"train_number": "19418",
			"train_name": "Ahmedabad - Borivali Express",
			"run_days": [
				"Mon",
				"Tue",
				"Wed",
				"Thu",
				"Fri",
				"Sat",
				"Sun"
			],
			"train_src": "ADI",
			"train_dstn": "BVI",
			"from_std": "02:50",
			"from_sta": "02:45",
			"local_train_from_sta": 1605,
			"to_sta": "06:01",
			"to_std": "06:06",
			"from_day": 1,
			"to_day": 1,
			"d_day": 1,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 13,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "3:11",
			"special_train": false,
			"train_type": "MEX",
			"score": 19,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 4,
			"score_duration": 4,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"SL"
			]
		},
		{
			"train_number": "19016",
			"train_name": "Saurashtra Express",
			"run_days": [
				"Mon",
				"Tue",
				"Wed",
				"Thu",
				"Fri",
				"Sat",
				"Sun"
			],
			"train_src": "PBR",
			"train_dstn": "DDR",
			"from_std": "10:01",
			"from_sta": "09:56",
			"local_train_from_sta": 2036,
			"to_sta": "13:12",
			"to_std": "13:17",
			"from_day": 1,
			"to_day": 1,
			"d_day": 1,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 11,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "3:11",
			"special_train": false,
			"train_type": "MEX",
			"score": 19,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 4,
			"score_duration": 4,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"SL",
				"3A",
				"2A"
			]
		},
		{
			"train_number": "09156",
			"train_name": "VADODARA - SURAT MEMU Special",
			"run_days": [
				"Mon",
				"Tue",
				"Wed",
				"Thu",
				"Fri",
				"Sat",
				"Sun"
			],
			"train_src": "BRC",
			"train_dstn": "ST",
			"from_std": "05:50",
			"from_sta": "05:50",
			"local_train_from_sta": 350,
			"to_sta": "09:15",
			"to_std": "09:15",
			"from_day": 0,
			"to_day": 0,
			"d_day": 0,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 22,
			"distance": 129,
			"to_station_name": "SURAT",
			"duration": "3:25",
			"special_valid_to": "2099-02-11",
			"special_train": true,
			"train_type": "MEMU",
			"score": 19,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 4,
			"score_duration": 4,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"2S"
			]
		},
		{
			"train_number": "59440",
			"train_name": "AHMEDABAD - MUMBAI CENTRAL Passenger",
			"run_days": [
				"Sun",
				"Mon",
				"Tue",
				"Wed",
				"Thu",
				"Fri",
				"Sat"
			],
			"train_src": "ADI",
			"train_dstn": "MMCT",
			"from_std": "02:43",
			"from_sta": "02:38",
			"local_train_from_sta": 1598,
			"to_sta": "07:05",
			"to_std": "07:20",
			"from_day": 1,
			"to_day": 1,
			"d_day": 1,
			"from": "BRC",
			"to": "ST",
			"from_station_name": "VADODARA JN",
			"halt_stn": 15,
			"distance": 129.7,
			"to_station_name": "SURAT",
			"duration": "4:22",
			"special_train": false,
			"train_type": "PASS",
			"score": 19,
			"score_train_type": 5,
			"score_booking_requency": 0,
			"frequency_perc": 0,
			"from_distance_text": "",
			"to_distance_text": "",
			"duration_rating": 5,
			"score_duration": 4,
			"score_std": 10,
			"score_user_preferred": 0,
			"train_date": "20-02-2024",
			"class_type": [
				"SL"
			]
		}
	]
}


export const HomePage = () => {
	const [toStation, setToStation] = useState('');
	const [fromStation, setFromStation] = useState('');
	const [journeyDate, setDate] = useState('');
	const [trainClass, setClass] = useState('');
	const [Category, setCategory] = useState('');
	const [trainDetails, setData] = useState([[]]);
	const [isData, setisData] = useState(undefined);
	const options = {
		method: 'GET',
		url: 'https://irctc1.p.rapidapi.com/api/v3/trainBetweenStations',
		params: {
			fromStationCode: fromStation,
			toStationCode: toStation,
			dateOfJourney: journeyDate
		},
		headers: {
			'X-RapidAPI-Key': 'b4e70a699amsh14ca2c7b34873bfp17c5b7jsn42b9d3f300ca',
			'X-RapidAPI-Host': 'irctc1.p.rapidapi.com'
		}
	};

	

	const train_API = async () => {
		try {
			console.log(options);
			// const response = await axios.request(options);
			console.log(traindata);
			setData(traindata.data)
			setisData(true);
			// console.log(trainDetails);
		} catch (error) {
			setisData(false);
			console.error(error);
		}
	}

	useEffect(() => {
		console.log(trainDetails);
	}, [trainDetails]);



	return (
		<div>
			<Navbar />

				<div className='booking_input' id='booking_input'>
					<div className='selection'>
						<label htmlFor="from">FROM</label>
						<input type="text" list='city' name='from' value={fromStation} onChange={(e) => { setFromStation(e.target.value) }} required />
					</div>
					{/* <button id='shift'></button> */}
					<div className='selection'>
						<label htmlFor="to">TO</label>
						<input type="text" list='city' name='to' value={toStation} onChange={(e) => { setToStation(e.target.value) }} required />
					</div>


					<datalist id='city'>
						<option value="ADI" >Ahmedabad </option>
						<option value="ST"  >Surat</option>
						<option value="BRC" >Vadodara</option>
						<option value="RJT" >Rajkot</option>
						<option value="MMCT">Mumbai</option>
						<option value="DLI" >Delhi</option>
						<option value="JP"  >Jaipur</option>
					</datalist>
				</div>

				<div className='booking_input' id='booking_input'>
					<div className='selection'>
						<label htmlFor="date">DATE</label>
						<input required type="date" name='Date' value={journeyDate} onChange={(e) => { setDate(e.target.value) }} />
					</div>
					<div className='selection'>

						<label htmlFor="class">CLASS</label>
						<select required name="class" id="class_selection" value={trainClass} onChange={(e) => { setClass(e.target.value) }}>
							<option value="1A">1A</option>
							<option value="2A">2A</option>
							<option value="3A">3A</option>
							<option value="CCC">AC chair car </option>
							<option value="EC">Executive chair car </option>
							<option value="3E">Third AC economy</option>
							<option value="SL">Sleeper Class(SL)</option>
							<option value="2S">Second Class</option>
						</select>
					</div>
					<div className='selection'>

						<label htmlFor="categoty">Category</label>
						<select name="class" id="category_selection" value={Category} onChange={(e) => { setCategory(e.target.value) }}>
							<option value="All_classes">All Classes</option>
							<option value="General">General</option>
							<option value="AC">AC</option>
							<option value="Non-AC">Non-AC</option>

						</select>
					</div>


				</div>
			<div id='searchtrain'>
				<button id='submitbtn' type='submit' onClick={train_API}>Search</button>
			</div>

			{isData !== undefined && <div className='train_details'>
				{trainDetails.map((train, index) => (
					isData ? <Card key={index} data={train} class={trainClass}/> : <h1 style={{margin:30}}>No Data Available</h1>
				))}
			</div>}

				
		</div>
	)
}

export default HomePage;